---
branches:
  only:
  - master
  - develop
language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "7"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "8"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "9"
after_success:
  - npm run coveralls
